version: '3'

services:
  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    ports:
      - 8080:8080  
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/local_guide
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    ports:
      - 81:80 
    depends_on:
      - backend

  mysql:
    image: mysql:latest
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: local_guide
    ports:
          - "3306:3306"